---
title: "Exploratory Data Analysis: Project 1 Notebook"
author: "James Sanders"
date: "July 9, 2014"
output: html_document
---

## Getting the data

First we download and unzip the data file if necessary:

```{r}
url <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
zipfile <- "data/household_power_consumption.zip"
if(!file.exists(zipfile)) { download.file(url, destfile = zipfile, method = "curl", quiet = TRUE) }
txtfile <- "data/household_power_consumption.txt"
if(!file.exists(txtfile)) { unzip(zipfile, exdir = "data") }
```

Now we read in just the portion of the data for 02-01-2007 and 02-02-2007, and add a DateTime column that combines the Date and Time columns into a proper POSIXlt:

```{r, cache = TRUE}
if(!exists("powerData")) {
  library(sqldf)
  powerData <- read.csv2.sql(txtfile, 'SELECT * FROM file WHERE Date IN ("1/2/2007", "2/2/2007")')
}
powerData$DateTime <- strptime(paste(powerData$Date, powerData$Time), "%d/%m/%Y %X")
```

## Plot 1

```{r, fig.width=480, fig.height=480}
hist(powerData$Global_active_power,
     col = "red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
```

## Plot 2

```{r, fig.width=480, fig.height=480}
plot(powerData$DateTime, powerData$Global_active_power,
     type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
```

## Plot 3

```{r, fig.width=480, fig.height=480}
plot(powerData$DateTime, powerData$Sub_metering_1,
     type = "l", xlab = "", ylab = "Energy sub metering")
lines(powerData$DateTime, powerData$Sub_metering_2,
      type = "l", col = "red")
lines(powerData$DateTime, powerData$Sub_metering_3,
      type = "l", col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),
       col = c("black", "red", "blue"), lty = 1)
```

## Plot 4

```{r, fig.width=480, fig.height=480}
par(mfrow = c(2,2))

# Top left
plot(powerData$DateTime, powerData$Global_active_power,
     xlab = "", ylab = "Global Active Power", type = "l")

# Top right
plot(powerData$DateTime, powerData$Voltage,
     xlab = "datetime", ylab = "Voltage", type = "l")

# Bottom left
plot(powerData$DateTime, powerData$Sub_metering_1,
     type = "l", xlab = "", ylab = "Energy sub metering")
lines(powerData$DateTime, powerData$Sub_metering_2,
      type = "l", col = "red")
lines(powerData$DateTime, powerData$Sub_metering_3,
      type = "l", col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),
       col = c("black", "red", "blue"), lty = 1, bty = "n", cex = 0.8)

# Bottom right
plot(powerData$DateTime, powerData$Global_reactive_power,
     xlab = "datetime", ylab = "Global_reactive_power", type = "l")
```


